### PR TITLE
Add eslint-plugin-require-sort

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Add eslint-plugin-require-sort
- [x] Update rules

### 🗒 Notes
- because of nature of our project this plugin and it's rules show be disabled in certain modules.

### CODE REVIEW

**Comment by marjev** [comment]
Any progress? NTC has high hopes 🚀

**Comment by zcuric** [comment]
@vladimyr Shall we?

**Comment by vladimyr** [comment]
Let's do it 🚢

**Comment by vladimyr** [comment]
Published as [`1.2.0`](https://www.npmjs.com/package/@extensionengine/eslint-config/v/1.2.0) 🎉

**Pull request merged**
